#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = %cd%

CC = gcc.exe
CXX = g++.exe
AR = ar.exe
LD = g++.exe
WINDRES = windres.exe

INC = 
CFLAGS = 
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -Wall -std=c++14 -m32 -g -fopenmp -DBUILD_DLL -D__InputKB_00010419
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB) 
LDFLAGS_DEBUG = $(LDFLAGS) -static-libstdc++ -static-libgcc -static -m32 -lgomp -lgdi32 -luser32
OBJDIR_DEBUG = obj\\Debug
DEP_DEBUG = 
DEF_DEBUG = bin\\Debug\\GameDev.def
SHAREDINT_DEBUG = bin\\Debug\\libGameDev.a
OUT_DEBUG = bin\\Debug\\GameDev.dll

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2 -Wextra -Wall -std=c++14 -m32 -fopenmp -DBUILD_DLL -D__InputKB_00010419
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB) -luser32
LDFLAGS_RELEASE = $(LDFLAGS) -s -static-libstdc++ -static-libgcc -static -m32 -lgomp -lgdi32 -luser32
OBJDIR_RELEASE = obj\\Release
DEP_RELEASE = 
DEF_RELEASE = bin\\Release\\GameDev.def
SHAREDINT_RELEASE = bin\\Release\\libGameDev.a
OUT_RELEASE = bin\\Release\\GameDev.dll

OBJ_DEBUG = $(OBJDIR_DEBUG)\\InputLang.o \
	$(OBJDIR_DEBUG)\\loader.o \
	$(OBJDIR_DEBUG)\\Wnd.o \
	$(OBJDIR_DEBUG)\\InputMouseBW.o \
	$(OBJDIR_DEBUG)\\InputMouseAW.o \
	$(OBJDIR_DEBUG)\\API\\GameDevClass.o \
	$(OBJDIR_DEBUG)\\InputKey.o \
	$(OBJDIR_DEBUG)\\HBitMap.o \
	$(OBJDIR_DEBUG)\\BitMap.o

OBJ_RELEASE = $(OBJDIR_RELEASE)\\InputLang.o \
	$(OBJDIR_RELEASE)\\loader.o \
	$(OBJDIR_RELEASE)\\Wnd.o \
	$(OBJDIR_RELEASE)\\InputMouseBW.o \
	$(OBJDIR_RELEASE)\\InputMouseAW.o \
	$(OBJDIR_RELEASE)\\API\\GameDevClass.o \
	$(OBJDIR_RELEASE)\\InputKey.o \
	$(OBJDIR_RELEASE)\\HBitMap.o \
	$(OBJDIR_RELEASE)\\BitMap.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	cmd /c if not exist bin\\Debug md bin\\Debug
	cmd /c if not exist $(OBJDIR_DEBUG) md $(OBJDIR_DEBUG)
	cmd /c if not exist $(OBJDIR_DEBUG)\\API md $(OBJDIR_DEBUG)\\API

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) -shared $(LIBDIR_DEBUG) $(OBJ_DEBUG)  -o $(OUT_DEBUG) $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)\\InputLang.o: InputLang.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c InputLang.cpp -o $(OBJDIR_DEBUG)\\InputLang.o

$(OBJDIR_DEBUG)\\loader.o: loader.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c loader.cpp -o $(OBJDIR_DEBUG)\\loader.o

$(OBJDIR_DEBUG)\\Wnd.o: Wnd.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Wnd.cpp -o $(OBJDIR_DEBUG)\\Wnd.o

$(OBJDIR_DEBUG)\\InputMouseBW.o: InputMouseBW.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c InputMouseBW.cpp -o $(OBJDIR_DEBUG)\\InputMouseBW.o

$(OBJDIR_DEBUG)\\InputMouseAW.o: InputMouseAW.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c InputMouseAW.cpp -o $(OBJDIR_DEBUG)\\InputMouseAW.o

$(OBJDIR_DEBUG)\\API\\GameDevClass.o: API\\GameDevClass.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c API\\GameDevClass.cpp -o $(OBJDIR_DEBUG)\\API\\GameDevClass.o

$(OBJDIR_DEBUG)\\InputKey.o: InputKey.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c InputKey.cpp -o $(OBJDIR_DEBUG)\\InputKey.o

$(OBJDIR_DEBUG)\\HBitMap.o: HBitMap.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c HBitMap.cpp -o $(OBJDIR_DEBUG)\\HBitMap.o

$(OBJDIR_DEBUG)\\BitMap.o: BitMap.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c BitMap.cpp -o $(OBJDIR_DEBUG)\\BitMap.o

clean_debug: 
	cmd /c del /f $(OBJ_DEBUG) $(OUT_DEBUG)
	cmd /c rd $(OBJDIR_DEBUG)
	cmd /c rd $(OBJDIR_DEBUG)\\API

before_release: 
	cmd /c if not exist bin\\Release md bin\\Release
	cmd /c if not exist $(OBJDIR_RELEASE) md $(OBJDIR_RELEASE)
	cmd /c if not exist $(OBJDIR_RELEASE)\\API md $(OBJDIR_RELEASE)\\API

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) -shared $(LIBDIR_RELEASE) $(OBJ_RELEASE)  -o $(OUT_RELEASE) $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)\\InputLang.o: InputLang.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c InputLang.cpp -o $(OBJDIR_RELEASE)\\InputLang.o

$(OBJDIR_RELEASE)\\loader.o: loader.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c loader.cpp -o $(OBJDIR_RELEASE)\\loader.o

$(OBJDIR_RELEASE)\\Wnd.o: Wnd.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Wnd.cpp -o $(OBJDIR_RELEASE)\\Wnd.o

$(OBJDIR_RELEASE)\\InputMouseBW.o: InputMouseBW.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c InputMouseBW.cpp -o $(OBJDIR_RELEASE)\\InputMouseBW.o

$(OBJDIR_RELEASE)\\InputMouseAW.o: InputMouseAW.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c InputMouseAW.cpp -o $(OBJDIR_RELEASE)\\InputMouseAW.o

$(OBJDIR_RELEASE)\\API\\GameDevClass.o: API\\GameDevClass.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c API\\GameDevClass.cpp -o $(OBJDIR_RELEASE)\\API\\GameDevClass.o

$(OBJDIR_RELEASE)\\InputKey.o: InputKey.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c InputKey.cpp -o $(OBJDIR_RELEASE)\\InputKey.o

$(OBJDIR_RELEASE)\\HBitMap.o: HBitMap.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c HBitMap.cpp -o $(OBJDIR_RELEASE)\\HBitMap.o

$(OBJDIR_RELEASE)\\BitMap.o: BitMap.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c BitMap.cpp -o $(OBJDIR_RELEASE)\\BitMap.o

clean_release: 
	cmd /c del /f $(OBJ_RELEASE) $(OUT_RELEASE)
	cmd /c rd $(OBJDIR_RELEASE)
	cmd /c rd $(OBJDIR_RELEASE)\\API

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

